### ISSUE TITLE
Dead Co-op Ghost Players can use Evil Beggars infinitely

### ISSUE THREAD

**Issue by BoardAnims** [Erfly/fiendfolio-issues#85]
**Describe the bug**
A dead ghost co-op player can walk up to an Evil Beggar and use it infinitely. This does not drain their HP in any way, even when they respawn.

**To Reproduce**
1. Play Co-op/Multiplayer.
2. Have at least one person die and become a ghost helper.
3. Find an Evil Beggar.
4. Make the baby ghost player walk up and interact with the Evil Beggar.

**Console Errors and Logs**
N/A

**Screenshots**

https://github.com/user-attachments/assets/f23a1003-242a-4c0e-95cb-8c248c00fa2c

**Additional context**
After some testing, it actually seems like ALL of Fiend Folio's machines can be used by co-op ghosts. If the machine is used it will substract the required pickup and use the machine as normal.

**Comment by catinsurance** [comment]
fixed in an upcoming patch
